harnessApiVersion: '1.0'
type: BUILD
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupNames:
  - Account Administrator
phases:
- daemonSet: false
  name: Phase 1
  phaseSteps:
  - type: PREPARE_STEPS
    name: Prepare Steps
    steps:
    - type: GCB
      name: Google Cloud Build
      properties:
        executeWithPreviousSteps: false
        gcbOptions:
          specSource: INLINE
          inlineSpec: '{}'
          gcpConfigName: fd-gcp
        sweepingOutputName: null
        sweepingOutputScope: null
        timeoutMillis: 600000
    stepsInParallel: false
  - type: COLLECT_ARTIFACT
    name: Collect Artifact
    steps:
    - type: ARTIFACT_COLLECTION
      name: Artifact Collection
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  statefulSet: false
templatized: false
